import { readFile, writeFile } from "node:fs/promises";
import geoTo3D from "./geoTo3D.ts";
import {
  type GeoJsonObject,
  getLines,
  type Position,
  projectFlatCoordinate,
  roundValue,
} from "./helpers/blenderProjection.ts";

/** A fitted flat projection that converts longitude/latitude coordinates to x/y coordinates. */
export type GeoToBlenderFlatProjection = (
  coordinates: [number, number],
) => [number, number] | null;

/** A projection function or `"orthographic"` for 3D globe borders. */
export type GeoToBlenderProjection =
  | "orthographic"
  | GeoToBlenderFlatProjection;

/** Options for converting GeoJSON borders into a Blender OBJ file. */
export type GeoToBlenderOptions = {
  /**
   * For `"orthographic"`, the radius of the sphere in Blender units.
   * @default 10
   */
  radius?: number;
  /**
   * The number of decimal places to round OBJ coordinates to.
   */
  decimals?: number;
  /**
   * The maximum angular distance, in degrees, between generated vertices for `"orthographic"`.
   * By default, segments are not densified.
   */
  maxSegmentLength?: number;
};

type GreatCircleInterpolator = ((t: number) => Position) & {
  distance: number;
};

// Adapted from d3-geo's spherical great-circle interpolation.
function interpolateGreatCircle(
  start: Position,
  end: Position,
): GreatCircleInterpolator {
  const radians = Math.PI / 180;
  const degrees = 180 / Math.PI;
  const x0 = start[0] * radians;
  const y0 = start[1] * radians;
  const x1 = end[0] * radians;
  const y1 = end[1] * radians;
  const cy0 = Math.cos(y0);
  const sy0 = Math.sin(y0);
  const cy1 = Math.cos(y1);
  const sy1 = Math.sin(y1);
  const kx0 = cy0 * Math.cos(x0);
  const ky0 = cy0 * Math.sin(x0);
  const kx1 = cy1 * Math.cos(x1);
  const ky1 = cy1 * Math.sin(x1);
  const haversin = (value: number) => Math.sin(value / 2) ** 2;
  const asin = (value: number) =>
    value > 1 ? Math.PI / 2 : value < -1 ? -Math.PI / 2 : Math.asin(value);
  const distance = 2 * asin(Math.sqrt(
    haversin(y1 - y0) + cy0 * cy1 * haversin(x1 - x0),
  ));
  const k = Math.sin(distance);

  const interpolate = (distance
    ? (t: number): Position => {
      const b = Math.sin(t * distance) / k;
      const a = Math.sin(distance - t * distance) / k;
      const x = a * kx0 + b * kx1;
      const y = a * ky0 + b * ky1;
      const z = a * sy0 + b * sy1;

      return [
        Math.atan2(y, x) * degrees,
        Math.atan2(z, Math.sqrt(x * x + y * y)) * degrees,
      ];
    }
    : (): Position => [start[0], start[1]]) as GreatCircleInterpolator;

  interpolate.distance = distance;
  return interpolate;
}

function vertexLine(
  x: number,
  y: number,
  z: number,
  decimals?: number,
): string {
  return `v ${roundValue(x, decimals)} ${roundValue(y, decimals)} ${
    roundValue(z, decimals)
  }`;
}

function toObj(lines: [number, number, number][][], decimals?: number): string {
  const output = ["# Generated by @nshiab/journalism-geo", "o borders"];
  let vertexIndex = 1;

  for (const line of lines) {
    if (line.length < 2) {
      continue;
    }

    const indexes = [];

    for (const [x, y, z] of line) {
      output.push(vertexLine(x, y, z, decimals));
      indexes.push(vertexIndex);
      vertexIndex += 1;
    }

    output.push(`l ${indexes.join(" ")}`);
  }

  return `${output.join("\n")}\n`;
}

function densifyLine(line: Position[], maxSegmentLength: number): Position[] {
  if (line.length < 2) {
    return line;
  }

  const densified = [line[0]];

  for (let index = 1; index < line.length; index += 1) {
    const start = line[index - 1];
    const end = line[index];
    const interpolate = interpolateGreatCircle(start, end);
    const distanceDegrees = interpolate.distance * (180 / Math.PI);
    const segments = Math.max(
      1,
      Math.ceil(distanceDegrees / maxSegmentLength),
    );

    for (let segment = 1; segment <= segments; segment += 1) {
      densified.push(interpolate(segment / segments) as Position);
    }
  }

  return densified;
}

/**
 * Converts GeoJSON borders into an OBJ file that can be imported in Blender.
 *
 * Polygon rings, MultiPolygon rings, LineStrings, and MultiLineStrings are exported as OBJ line geometry.
 * Polygon and MultiPolygon rings are always closed into loops (a closing coordinate is appended when the source data omits it), while LineStrings and MultiLineStrings are left exactly as provided.
 * Flat projection functions are placed on Blender's X/Y plane with Z up and north toward positive Y.
 * The `"orthographic"` projection exports borders in 3D on a sphere using `geoTo3D`.
 * Set `maxSegmentLength` to add extra vertices along long orthographic segments.
 *
 * When fitting a flat projection with `fitExtent`/`fitSize`, run the GeoJSON through {@link rewind} first. Many data sources wind their polygons the wrong way for `d3-geo`, which makes the fit collapse to a near-zero scale and produces an empty-looking OBJ.
 *
 * @param geojsonPath - The path to the GeoJSON file to convert.
 * @param projection - A flat projection function or `"orthographic"` for 3D globe borders.
 * @param outputPath - The path where the OBJ file will be written.
 * @param options - Optional settings for orthographic radius, coordinate rounding, and orthographic segment densification.
 * @returns A Promise that resolves to the output path.
 *
 * @example
 * ```ts
 * import { geoToBlender, rewind } from "@nshiab/journalism-geo";
 * import { geoConicConformal } from "d3-geo";
 * import { readFile } from "node:fs/promises";
 *
 * const geojsonPath = "./data/canada.geojson";
 * const geojson = JSON.parse(await readFile(geojsonPath, "utf8"));
 * // Rewind so fitExtent measures the real extent instead of collapsing.
 * const domain = rewind(geojson);
 * const projection = geoConicConformal()
 *   .rotate([100, -60])
 *   .fitExtent([[-5, -5], [5, 5]], domain);
 * await geoToBlender(geojsonPath, projection, "./output/canada.obj", {
 *   decimals: 3,
 * });
 * ```
 * @category Geo
 */
export default async function geoToBlender(
  geojsonPath: string,
  projection:
    | "orthographic"
    | ((coordinates: [number, number]) => [number, number] | null),
  outputPath: string,
  options: {
    /**
     * For `"orthographic"`, the radius of the sphere in Blender units.
     * @default 10
     */
    radius?: number;
    /**
     * The number of decimal places to round OBJ coordinates to.
     */
    decimals?: number;
    /**
     * The maximum angular distance, in degrees, between generated vertices for `"orthographic"`.
     * By default, segments are not densified.
     */
    maxSegmentLength?: number;
  } = {},
): Promise<string> {
  const radius = options.radius ?? 10;
  const geojson = JSON.parse(
    await readFile(geojsonPath, "utf8"),
  ) as GeoJsonObject;
  const lines = getLines(geojson);

  let objLines: [number, number, number][][];

  if (projection === "orthographic") {
    objLines = lines.map((line) =>
      (typeof options.maxSegmentLength === "number"
        ? densifyLine(line, options.maxSegmentLength)
        : line).map(([lon, lat]) =>
          geoTo3D(lon, lat, radius, {
            decimals: options.decimals,
            toArray: true,
          })
        )
    );
  } else {
    objLines = lines.map((line) =>
      line.flatMap(([lon, lat]) => {
        const projected = projectFlatCoordinate(
          projection,
          lon,
          lat,
          options.decimals,
        );

        if (projected === null) {
          return [];
        }

        return [projected];
      })
    );
  }

  await writeFile(outputPath, toObj(objLines, options.decimals));

  return outputPath;
}
