import { geoDistance, geoInterpolate } from "d3-geo";
import { readFile, writeFile } from "node:fs/promises";
import geoTo3D from "./geoTo3D.ts";
import {
  fitProjection,
  type GeoJsonObject,
  getLines,
  linesToGeoJson,
  type Position,
  projectFlatCoordinate,
  roundValue,
} from "./helpers/geoToBlender.ts";

/** Rotation angles for flat d3-geo projections, in degrees. */
export type { GeoToBlenderRotate } from "./helpers/geoToBlender.ts";

/** The supported projection names for `geoToBlender`. */
export type { GeoToBlenderProjection } from "./helpers/geoToBlender.ts";

/** Options for converting GeoJSON borders into a Blender OBJ file. */
export type GeoToBlenderOptions = {
  /**
   * For flat projections, the width and height of the fitted projection extent in Blender units.
   * For `"orthographic"`, the radius of the sphere in Blender units.
   * @default 10
   */
  scale?: number;
  /**
   * The number of decimal places to round OBJ coordinates to.
   */
  decimals?: number;
  /**
   * Rotation angles for flat d3-geo projections, in degrees.
   * These values are passed to the projection's `rotate` method before fitting.
   */
  rotate?: [number, number] | [number, number, number];
  /**
   * The maximum angular distance, in degrees, between generated vertices for `"orthographic"`.
   * By default, segments are not densified.
   */
  maxSegmentLength?: number;
};

function vertexLine(
  x: number,
  y: number,
  z: number,
  decimals?: number,
): string {
  return `v ${roundValue(x, decimals)} ${roundValue(y, decimals)} ${
    roundValue(z, decimals)
  }`;
}

function toObj(lines: [number, number, number][][], decimals?: number): string {
  const output = ["# Generated by @nshiab/journalism-geo", "o borders"];
  let vertexIndex = 1;

  for (const line of lines) {
    if (line.length < 2) {
      continue;
    }

    const indexes = [];

    for (const [x, y, z] of line) {
      output.push(vertexLine(x, y, z, decimals));
      indexes.push(vertexIndex);
      vertexIndex += 1;
    }

    output.push(`l ${indexes.join(" ")}`);
  }

  return `${output.join("\n")}\n`;
}

function densifyLine(line: Position[], maxSegmentLength: number): Position[] {
  if (line.length < 2) {
    return line;
  }

  const densified = [line[0]];

  for (let index = 1; index < line.length; index += 1) {
    const start = line[index - 1];
    const end = line[index];
    const distance = geoDistance(start, end) * (180 / Math.PI);
    const segments = Math.max(1, Math.ceil(distance / maxSegmentLength));
    const interpolate = geoInterpolate(start, end);

    for (let segment = 1; segment <= segments; segment += 1) {
      densified.push(interpolate(segment / segments) as Position);
    }
  }

  return densified;
}

/**
 * Converts GeoJSON borders into an OBJ file that can be imported in Blender.
 *
 * Polygon rings, MultiPolygon rings, LineStrings, and MultiLineStrings are exported as OBJ line geometry.
 * Flat projections are fitted to the full GeoJSON extent and placed on Blender's X/Y plane with Z up.
 * The `"orthographic"` projection exports borders in 3D on a sphere using `geoTo3D`.
 * Set `maxSegmentLength` to add extra vertices along long orthographic segments.
 *
 * @param geojsonPath - The path to the GeoJSON file to convert.
 * @param projection - The projection to use. Supports d3-geo conic and cylindrical projection names, plus `"orthographic"` for 3D globe borders.
 * @param outputPath - The path where the OBJ file will be written.
 * @param options - Optional settings for scale and coordinate rounding.
 * @returns A Promise that resolves to the output path.
 *
 * @example
 * ```ts
 * await geoToBlender("./data/canada.geojson", "mercator", "./output/canada.obj", {
 *   scale: 10,
 *   decimals: 3,
 * });
 * ```
 * @category Geo
 */
export default async function geoToBlender(
  geojsonPath: string,
  projection:
    | "albers"
    | "albersUsa"
    | "conicConformal"
    | "conicEqualArea"
    | "conicEquidistant"
    | "equirectangular"
    | "equalEarth"
    | "mercator"
    | "naturalEarth1"
    | "orthographic"
    | "transverseMercator",
  outputPath: string,
  options: {
    /**
     * For flat projections, the width and height of the fitted projection extent in Blender units.
     * For `"orthographic"`, the radius of the sphere in Blender units.
     * @default 10
     */
    scale?: number;
    /**
     * The number of decimal places to round OBJ coordinates to.
     */
    decimals?: number;
    /**
     * Rotation angles for flat d3-geo projections, in degrees.
     * These values are passed to the projection's `rotate` method before fitting.
     */
    rotate?: [number, number] | [number, number, number];
    /**
     * The maximum angular distance, in degrees, between generated vertices for `"orthographic"`.
     * By default, segments are not densified.
     */
    maxSegmentLength?: number;
  } = {},
): Promise<string> {
  const scale = options.scale ?? 10;
  const geojson = JSON.parse(
    await readFile(geojsonPath, "utf8"),
  ) as GeoJsonObject;
  const lines = getLines(geojson);

  let objLines: [number, number, number][][];

  if (projection === "orthographic") {
    objLines = lines.map((line) =>
      (typeof options.maxSegmentLength === "number"
        ? densifyLine(line, options.maxSegmentLength)
        : line).map(([lon, lat]) =>
          geoTo3D(lon, lat, scale, {
            decimals: options.decimals,
            toArray: true,
          })
        )
    );
  } else {
    const d3Projection = fitProjection(
      projection,
      linesToGeoJson(lines),
      scale,
      options.rotate,
    );

    objLines = lines.map((line) =>
      line.flatMap(([lon, lat]) => {
        const projected = projectFlatCoordinate(
          d3Projection,
          lon,
          lat,
          options.decimals,
        );

        if (projected === null) {
          return [];
        }

        return [projected];
      })
    );
  }

  await writeFile(outputPath, toObj(objLines, options.decimals));

  return outputPath;
}
