import {
  geoAlbers,
  geoAlbersUsa,
  geoConicConformal,
  geoConicEqualArea,
  geoConicEquidistant,
  geoDistance,
  geoEqualEarth,
  geoEquirectangular,
  geoInterpolate,
  geoMercator,
  geoNaturalEarth1,
  geoTransverseMercator,
} from "d3-geo";
import geoTo3D from "./geoTo3D.ts";

type Position = [number, number] | [number, number, number];

type GeoJsonGeometry =
  | { type: "Point"; coordinates: Position }
  | { type: "MultiPoint"; coordinates: Position[] }
  | { type: "LineString"; coordinates: Position[] }
  | { type: "MultiLineString"; coordinates: Position[][] }
  | { type: "Polygon"; coordinates: Position[][] }
  | { type: "MultiPolygon"; coordinates: Position[][][] }
  | { type: "GeometryCollection"; geometries: GeoJsonGeometry[] };

type GeoJsonObject =
  | GeoJsonGeometry
  | { type: "Feature"; geometry: GeoJsonGeometry | null }
  | {
    type: "FeatureCollection";
    features: { geometry: GeoJsonGeometry | null }[];
  };

type FlatProjection = {
  fitExtent: (
    extent: [[number, number], [number, number]],
    object: GeoJsonObject,
  ) => FlatProjection;
  (coordinates: [number, number]): [number, number] | null;
};

/** The supported projection names for `geoToBlender`. */
export type GeoToBlenderProjection =
  | "albers"
  | "albersUsa"
  | "conicConformal"
  | "conicEqualArea"
  | "conicEquidistant"
  | "equirectangular"
  | "equalEarth"
  | "mercator"
  | "naturalEarth1"
  | "orthographic"
  | "transverseMercator";

/** Options for converting GeoJSON borders into a Blender OBJ file. */
export type GeoToBlenderOptions = {
  /**
   * For flat projections, the width and height of the fitted projection extent in Blender units.
   * For `"orthographic"`, the radius of the sphere in Blender units.
   * @default 10
   */
  scale?: number;
  /**
   * The number of decimal places to round OBJ coordinates to.
   */
  decimals?: number;
  /**
   * The maximum angular distance, in degrees, between generated vertices for `"orthographic"`.
   * @default 1
   */
  maxSegmentLength?: number;
};

function getProjection(
  projection: Exclude<GeoToBlenderProjection, "orthographic">,
) {
  if (projection === "albers") {
    return geoAlbers() as FlatProjection;
  }

  if (projection === "albersUsa") {
    return geoAlbersUsa() as FlatProjection;
  }

  if (projection === "conicConformal") {
    return geoConicConformal() as FlatProjection;
  }

  if (projection === "conicEqualArea") {
    return geoConicEqualArea() as FlatProjection;
  }

  if (projection === "conicEquidistant") {
    return geoConicEquidistant() as FlatProjection;
  }

  if (projection === "mercator") {
    return geoMercator() as FlatProjection;
  }

  if (projection === "equalEarth") {
    return geoEqualEarth() as FlatProjection;
  }

  if (projection === "equirectangular") {
    return geoEquirectangular() as FlatProjection;
  }

  if (projection === "transverseMercator") {
    return geoTransverseMercator() as FlatProjection;
  }

  return geoNaturalEarth1() as FlatProjection;
}

function getLines(geojson: GeoJsonObject): Position[][] {
  if (geojson.type === "FeatureCollection") {
    return geojson.features.flatMap((feature) =>
      feature.geometry ? getLines(feature.geometry) : []
    );
  }

  if (geojson.type === "Feature") {
    return geojson.geometry ? getLines(geojson.geometry) : [];
  }

  if (geojson.type === "LineString") {
    return [geojson.coordinates];
  }

  if (geojson.type === "MultiLineString" || geojson.type === "Polygon") {
    return geojson.coordinates;
  }

  if (geojson.type === "MultiPolygon") {
    return geojson.coordinates.flat();
  }

  if (geojson.type === "GeometryCollection") {
    return geojson.geometries.flatMap((geometry) => getLines(geometry));
  }

  return [];
}

function roundValue(value: number, decimals?: number): number {
  if (typeof decimals === "number") {
    return parseFloat(value.toFixed(decimals));
  }

  return value;
}

function vertexLine(
  x: number,
  y: number,
  z: number,
  decimals?: number,
): string {
  return `v ${roundValue(x, decimals)} ${roundValue(y, decimals)} ${
    roundValue(z, decimals)
  }`;
}

function toObj(lines: [number, number, number][][], decimals?: number): string {
  const output = ["# Generated by @nshiab/journalism-geo", "o borders"];
  let vertexIndex = 1;

  for (const line of lines) {
    if (line.length < 2) {
      continue;
    }

    const indexes = [];

    for (const [x, y, z] of line) {
      output.push(vertexLine(x, y, z, decimals));
      indexes.push(vertexIndex);
      vertexIndex += 1;
    }

    output.push(`l ${indexes.join(" ")}`);
  }

  return `${output.join("\n")}\n`;
}

function densifyLine(line: Position[], maxSegmentLength: number): Position[] {
  if (line.length < 2) {
    return line;
  }

  const densified = [line[0]];

  for (let index = 1; index < line.length; index += 1) {
    const start = line[index - 1];
    const end = line[index];
    const distance = geoDistance(start, end) * (180 / Math.PI);
    const segments = Math.max(1, Math.ceil(distance / maxSegmentLength));
    const interpolate = geoInterpolate(start, end);

    for (let segment = 1; segment <= segments; segment += 1) {
      densified.push(interpolate(segment / segments) as Position);
    }
  }

  return densified;
}

/**
 * Converts GeoJSON borders into an OBJ file that can be imported in Blender.
 *
 * Polygon rings, MultiPolygon rings, LineStrings, and MultiLineStrings are exported as OBJ line geometry.
 * Flat projections are fitted to the full GeoJSON extent and placed on Blender's X/Z plane with Y up.
 * The `"orthographic"` projection exports borders in 3D on a sphere using `geoTo3D`, with extra vertices added along long segments.
 *
 * @param geojsonPath - The path to the GeoJSON file to convert.
 * @param projection - The projection to use. Supports d3-geo conic and cylindrical projection names, plus `"orthographic"` for 3D globe borders.
 * @param outputPath - The path where the OBJ file will be written.
 * @param options - Optional settings for scale and coordinate rounding.
 * @returns A Promise that resolves to the output path.
 *
 * @example
 * ```ts
 * await geoToBlender("./data/canada.geojson", "mercator", "./output/canada.obj", {
 *   scale: 10,
 *   decimals: 3,
 * });
 * ```
 * @category Geo
 */
export default async function geoToBlender(
  geojsonPath: string,
  projection: GeoToBlenderProjection,
  outputPath: string,
  options: GeoToBlenderOptions = {},
): Promise<string> {
  const scale = options.scale ?? 10;
  const geojson = JSON.parse(
    await Deno.readTextFile(geojsonPath),
  ) as GeoJsonObject;
  const lines = getLines(geojson);

  let objLines: [number, number, number][][];

  if (projection === "orthographic") {
    const maxSegmentLength = options.maxSegmentLength ?? 1;

    objLines = lines.map((line) =>
      densifyLine(line, maxSegmentLength).map(([lon, lat]) =>
        geoTo3D(lon, lat, scale, {
          decimals: options.decimals,
          toArray: true,
        })
      )
    );
  } else {
    const d3Projection = getProjection(projection).fitExtent(
      [[-scale / 2, -scale / 2], [scale / 2, scale / 2]],
      geojson,
    );

    objLines = lines.map((line) =>
      line.flatMap(([lon, lat]) => {
        const projected = d3Projection([lon, lat]);

        if (projected === null) {
          return [];
        }

        const [x, z] = projected;
        return [[x, 0, z] as [number, number, number]];
      })
    );
  }

  await Deno.writeTextFile(outputPath, toObj(objLines, options.decimals));

  return outputPath;
}
