import { assert, assertEquals, assertStringIncludes } from "jsr:@std/assert";
import geoToBlender from "../../src/geo/geoToBlender.ts";

const outputDir = "test/output/geoToBlender";
const provincesPath = "test/data/lpr_000b21a_e.json";

const flatProjections = [
  "albers",
  "albersUsa",
  "conicConformal",
  "conicEqualArea",
  "conicEquidistant",
  "equalEarth",
  "equirectangular",
  "mercator",
  "naturalEarth1",
  "transverseMercator",
] as const;

const square = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      properties: {},
      geometry: {
        type: "Polygon",
        coordinates: [[
          [-1, -1],
          [1, -1],
          [1, 1],
          [-1, 1],
          [-1, -1],
        ]],
      },
    },
  ],
};

const usSquare = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      properties: {},
      geometry: {
        type: "Polygon",
        coordinates: [[
          [-101, 39],
          [-99, 39],
          [-99, 41],
          [-101, 41],
          [-101, 39],
        ]],
      },
    },
  ],
};

const rotatedSquare = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      properties: {},
      geometry: {
        type: "Polygon",
        coordinates: [[
          [0, 40],
          [10, 40],
          [10, 50],
          [0, 50],
          [0, 40],
        ]],
      },
    },
  ],
};

async function writeGeoJson(
  name: string,
  geojson: typeof square = square,
): Promise<string> {
  await Deno.mkdir(outputDir, { recursive: true });
  const path = `${outputDir}/${name}.geojson`;
  await Deno.writeTextFile(path, JSON.stringify(geojson));
  return path;
}

function vertexRange(obj: string, axis: 0 | 2): number {
  let min = Infinity;
  let max = -Infinity;

  for (const line of obj.split("\n")) {
    if (line.startsWith("v ")) {
      const value = Number(line.split(" ")[axis + 1]);
      min = Math.min(min, value);
      max = Math.max(max, value);
    }
  }

  return max - min;
}

function countObjRecords(obj: string, record: "v" | "l"): number {
  return obj.split("\n")
    .filter((line) => line.startsWith(`${record} `)).length;
}

for (const projection of flatProjections) {
  Deno.test(`should write ${projection} GeoJSON borders to an OBJ file`, async () => {
    const geojsonPath = await writeGeoJson(
      `square-${projection}`,
      projection === "albersUsa" ? usSquare : square,
    );
    const outputPath = `${outputDir}/square-${projection}.obj`;

    const result = await geoToBlender(geojsonPath, projection, outputPath, {
      scale: 10,
      decimals: 3,
    });
    const obj = await Deno.readTextFile(outputPath);

    assertEquals(result, outputPath);
    assertStringIncludes(obj, "# Generated by @nshiab/journalism-geo\n");
    assertStringIncludes(obj, "o borders\n");
    assertStringIncludes(obj, "l 1 2 3 4 5\n");
    assert(
      Math.max(vertexRange(obj, 0), vertexRange(obj, 2)) > 5,
    );
  });
}

Deno.test("should write orthographic GeoJSON borders as 3D vertices", async () => {
  const geojsonPath = await writeGeoJson("square-orthographic");
  const outputPath = `${outputDir}/square-orthographic.obj`;

  await geoToBlender(geojsonPath, "orthographic", outputPath, {
    scale: 1,
    decimals: 3,
  });
  const obj = await Deno.readTextFile(outputPath);

  assertStringIncludes(obj, "v -0.017 -0.017 1\n");
  assertStringIncludes(obj, "l 1 2 3 4 5\n");
});

Deno.test("should densify orthographic border segments when requested", async () => {
  const geojsonPath = await writeGeoJson("square-orthographic-densified");
  const outputPath = `${outputDir}/square-orthographic-densified.obj`;

  await geoToBlender(geojsonPath, "orthographic", outputPath, {
    scale: 1,
    decimals: 3,
    maxSegmentLength: 1,
  });
  const obj = await Deno.readTextFile(outputPath);

  assertStringIncludes(obj, "l 1 2 3 4 5 6 7 8 9\n");
});

Deno.test("should allow explicitly longer orthographic border segments", async () => {
  const geojsonPath = await writeGeoJson("square-orthographic-long-segments");
  const outputPath = `${outputDir}/square-orthographic-long-segments.obj`;

  await geoToBlender(geojsonPath, "orthographic", outputPath, {
    scale: 1,
    decimals: 3,
    maxSegmentLength: 10,
  });
  const obj = await Deno.readTextFile(outputPath);

  assertStringIncludes(obj, "l 1 2 3 4 5\n");
});

Deno.test("should rotate flat projections when requested", async () => {
  const geojsonPath = await writeGeoJson("square-rotated", rotatedSquare);
  const unrotatedPath = `${outputDir}/square-conicConformal-unrotated.obj`;
  const rotatedPath = `${outputDir}/square-conicConformal-rotated.obj`;

  await geoToBlender(geojsonPath, "conicConformal", unrotatedPath, {
    scale: 10,
    decimals: 3,
  });
  await geoToBlender(geojsonPath, "conicConformal", rotatedPath, {
    scale: 10,
    decimals: 3,
    rotate: [100, -60],
  });

  const unrotated = await Deno.readTextFile(unrotatedPath);
  const rotated = await Deno.readTextFile(rotatedPath);

  assert(unrotated !== rotated);
  assertStringIncludes(rotated, "v 5 0 2.545\n");
});

Deno.test("should write Canadian provinces and territories to an OBJ file", async () => {
  await Deno.mkdir(outputDir, { recursive: true });
  const outputPath = `${outputDir}/canada-provinces-territories.obj`;

  const result = await geoToBlender(provincesPath, "mercator", outputPath, {
    scale: 10,
    decimals: 3,
  });
  const obj = await Deno.readTextFile(outputPath);

  assertEquals(result, outputPath);
  assertStringIncludes(obj, "# Generated by @nshiab/journalism-geo\n");
  assertStringIncludes(obj, "o borders\n");
  assert(countObjRecords(obj, "v") > 1000);
  assert(countObjRecords(obj, "l") > 100);
  assert(
    Math.max(vertexRange(obj, 0), vertexRange(obj, 2)) > 5,
  );
});

Deno.test("should write Canadian provinces and territories to a conic conformal OBJ file", async () => {
  await Deno.mkdir(outputDir, { recursive: true });
  const outputPath =
    `${outputDir}/canada-provinces-territories-conicConformal.obj`;

  const result = await geoToBlender(
    provincesPath,
    "conicConformal",
    outputPath,
    {
      scale: 10,
      decimals: 3,
      rotate: [100, -60],
    },
  );
  const obj = await Deno.readTextFile(outputPath);

  assertEquals(result, outputPath);
  assertStringIncludes(obj, "# Generated by @nshiab/journalism-geo\n");
  assertStringIncludes(obj, "o borders\n");
  assert(countObjRecords(obj, "v") > 1000);
  assert(countObjRecords(obj, "l") > 100);
  assert(
    Math.max(vertexRange(obj, 0), vertexRange(obj, 2)) > 5,
  );
});

Deno.test("should write Canadian provinces and territories to an orthographic OBJ file", async () => {
  await Deno.mkdir(outputDir, { recursive: true });
  const outputPath =
    `${outputDir}/canada-provinces-territories-orthographic.obj`;

  const result = await geoToBlender(provincesPath, "orthographic", outputPath, {
    scale: 10,
    decimals: 3,
  });
  const obj = await Deno.readTextFile(outputPath);

  assertEquals(result, outputPath);
  assertStringIncludes(obj, "# Generated by @nshiab/journalism-geo\n");
  assertStringIncludes(obj, "o borders\n");
  assert(countObjRecords(obj, "v") > 1000);
  assert(countObjRecords(obj, "l") > 100);
  assert(vertexRange(obj, 0) > 5);
  assert(vertexRange(obj, 2) > 5);
});
