import { assertEquals, assertStringIncludes } from "jsr:@std/assert";
import geoToBlender from "../../src/geo/geoToBlender.ts";

const outputDir = "test/output/geoToBlender";

const flatProjections = [
  "albers",
  "albersUsa",
  "conicConformal",
  "conicEqualArea",
  "conicEquidistant",
  "equalEarth",
  "equirectangular",
  "mercator",
  "naturalEarth1",
  "transverseMercator",
] as const;

const square = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      properties: {},
      geometry: {
        type: "Polygon",
        coordinates: [[
          [-1, -1],
          [1, -1],
          [1, 1],
          [-1, 1],
          [-1, -1],
        ]],
      },
    },
  ],
};

const usSquare = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      properties: {},
      geometry: {
        type: "Polygon",
        coordinates: [[
          [-101, 39],
          [-99, 39],
          [-99, 41],
          [-101, 41],
          [-101, 39],
        ]],
      },
    },
  ],
};

async function writeGeoJson(
  name: string,
  geojson: typeof square = square,
): Promise<string> {
  await Deno.mkdir(outputDir, { recursive: true });
  const path = `${outputDir}/${name}.geojson`;
  await Deno.writeTextFile(path, JSON.stringify(geojson));
  return path;
}

for (const projection of flatProjections) {
  Deno.test(`should write ${projection} GeoJSON borders to an OBJ file`, async () => {
    const geojsonPath = await writeGeoJson(
      `square-${projection}`,
      projection === "albersUsa" ? usSquare : square,
    );
    const outputPath = `${outputDir}/square-${projection}.obj`;

    const result = await geoToBlender(geojsonPath, projection, outputPath, {
      scale: 10,
      decimals: 3,
    });
    const obj = await Deno.readTextFile(outputPath);

    assertEquals(result, outputPath);
    assertStringIncludes(obj, "# Generated by @nshiab/journalism-geo\n");
    assertStringIncludes(obj, "o borders\n");
    assertStringIncludes(obj, "l 1 2 3 4 5\n");
  });
}

Deno.test("should write orthographic GeoJSON borders as 3D vertices", async () => {
  const geojsonPath = await writeGeoJson("square-orthographic");
  const outputPath = `${outputDir}/square-orthographic.obj`;

  await geoToBlender(geojsonPath, "orthographic", outputPath, {
    scale: 1,
    decimals: 3,
  });
  const obj = await Deno.readTextFile(outputPath);

  assertStringIncludes(obj, "v -0.017 -0.017 1\n");
  assertStringIncludes(obj, "l 1 2 3 4 5 6 7 8 9\n");
});

Deno.test("should allow longer orthographic border segments", async () => {
  const geojsonPath = await writeGeoJson("square-orthographic-long-segments");
  const outputPath = `${outputDir}/square-orthographic-long-segments.obj`;

  await geoToBlender(geojsonPath, "orthographic", outputPath, {
    scale: 1,
    decimals: 3,
    maxSegmentLength: 10,
  });
  const obj = await Deno.readTextFile(outputPath);

  assertStringIncludes(obj, "l 1 2 3 4 5\n");
});
